import turtle

def fills(radius,rotation):##Not actual rotation but part of circle used (Ex:180 is half)
    turtle.begin_fill()
    turtle.circle(radius,rotation)
    turtle.end_fill()

def draw():
    radius = eval(input("Radius(>100): "))
    turtle.hideturtle()
    turtle.speed(0)
    turtle.pensize(3)
    turtle.color("black")
    fills(radius,180)
    turtle.color("black","white")
    fills(radius,180)
    turtle.color("black","white")
    fills(radius/2,180)
    turtle.color("black")
    turtle.pu()
    turtle.left(180)
    turtle.pd()
    fills(radius/2,360)
    turtle.color("white")
    turtle.pu()
    turtle.right(270)
    turtle.fd(radius/2)
    turtle.pd()
    fills(radius/10,360)
    turtle.color("black")
    turtle.pu()
    turtle.right(180)
    turtle.fd(radius)
    turtle.pd()
    fills(radius/10,360)
    turtle.hideturtle()

if __name__=='__main__':
    draw()
    turtle.exitonclick()
